apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: tech-challenge-group-4
  labels:
    name: postgres-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
