version: '3.8'

services:
  postgres:
    container_name: tech-challenger-pg
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tech-challenger
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tech-challenger-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: tech-challenger-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '5555:5555'
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: 'postgresql://postgres:docker@postgres:5432/tech-challenger'
      REDIS_URL: ${REDIS_URL}
      API_PORT: 3000
    networks:
      - tech-challenger-network

  redis:
    container_name: tech-challenger-redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - tech-challenger-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tech-challenger-network:
    driver: bridge

volumes:
  postgres-data:
